services:
  - type: web
    name: dbms-platform-server
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: GEMINI_API_KEY
        value: "AIzaSyCjMYlTMnXQsmsVGEDR1z7u_zpyUc5OV-Y"
